# Generated by Django 4.2.8 on 2023-12-09 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SE", "Sent"),
                            ("UR", "Under review"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                        ],
                        default="SE",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translator_request",
                        to="resume.resume",
                        verbose_name="resume",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslatorRequestStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from", max_length=2, verbose_name="from"
                    ),
                ),
                ("to", models.CharField(max_length=2, verbose_name="to")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "translator_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="translator_request.translatorrequest",
                        verbose_name="translator request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
