# Generated by Django 4.2.8 on 2023-12-21 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("translator_request", "0001_initial"),
        (
            "translator_request",
            "0002_alter_translatorrequeststatuslog_from_status_and_more",
        ),
        (
            "translator_request",
            "0003_translatorrequeststatuslog_comment_and_more",
        ),
        ("translator_request", "0004_remove_translatorrequest_resume"),
        (
            "translator_request",
            "0005_alter_translatorrequeststatuslog_timestamp",
        ),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SE", "Sent"),
                            ("UR", "Under review"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                        ],
                        default="SE",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslatorRequestStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("SE", "Sent"),
                            ("UR", "Under review"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                        ],
                        db_column="from",
                        max_length=2,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("SE", "Sent"),
                            ("UR", "Under review"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                        ],
                        max_length=2,
                        verbose_name="to status",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "translator_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="translator_request.translatorrequest",
                        verbose_name="translator request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="comment"
                    ),
                ),
            ],
        ),
    ]
