# Generated by Django 4.2.6 on 2023-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translator_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatorrequeststatuslog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("SE", "Sent"),
                    ("UR", "Under review"),
                    ("AC", "Accepted"),
                    ("RJ", "Rejected"),
                ],
                db_column="from",
                max_length=2,
                verbose_name="from status",
            ),
        ),
        migrations.AlterField(
            model_name="translatorrequeststatuslog",
            name="to",
            field=models.CharField(
                choices=[
                    ("SE", "Sent"),
                    ("UR", "Under review"),
                    ("AC", "Accepted"),
                    ("RJ", "Rejected"),
                ],
                max_length=2,
                verbose_name="to status",
            ),
        ),
    ]
