# Generated by Django 4.2.6 on 2023-12-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
        (
            "translator_request",
            "0002_alter_translatorrequeststatuslog_from_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="translatorrequeststatuslog",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="comment"
            ),
        ),
        migrations.AlterField(
            model_name="translatorrequest",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_request",
                to="resume.resume",
                verbose_name="resume",
            ),
        ),
    ]
