# Generated by Django 5.0 on 2023-12-19 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "translator_request",
            "0003_translatorrequeststatuslog_comment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translatorrequest",
            name="resume",
        ),
    ]
