# Generated by Django 4.2.8 on 2023-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translator_request", "0004_remove_translatorrequest_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatorrequeststatuslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="timestamp"
            ),
        ),
    ]
