# Generated by Django 4.2.8 on 2023-12-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("accounts", "0005_alter_account_native_lang"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="created at"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="closed at"
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SE", "Sent"),
                            ("AC", "Accepted"),
                            ("RJ", "Rejected"),
                            ("IP", "In progress"),
                            ("FN", "Finished"),
                            ("CL", "Closed"),
                        ],
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="price")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_requests_authored",
                        to="accounts.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_requests_translated",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslationRequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("timestamp", models.DateTimeField(verbose_name="timestamp")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
                (
                    "translation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translation_request.translationrequest",
                    ),
                ),
            ],
        ),
    ]
