# Generated by Django 4.2.8 on 2023-12-16 08:50

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("translation_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translationrequest",
            options={
                "verbose_name": "translation request",
                "verbose_name_plural": "translation requests",
            },
        ),
        migrations.AlterModelOptions(
            name="translationrequestmessage",
            options={
                "verbose_name": "translation request message",
                "verbose_name_plural": "translation request messages",
            },
        ),
        migrations.AddField(
            model_name="translationrequest",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="translationrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="translationrequest",
            name="price",
            field=djmoney.models.fields.MoneyField(
                currency_choices=(("USD", "Dollar"),),
                decimal_places=4,
                default_currency="USD",
                max_digits=19,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="translationrequestmessage",
            name="translation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                related_query_name="translation_request",
                to="translation_request.translationrequest",
            ),
        ),
    ]
