# Generated by Django 4.2.8 on 2023-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "translation_request",
            "0002_alter_translationrequest_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationrequestmessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="timestamp"
            ),
        ),
    ]
