# Generated by Django 4.2.8 on 2023-12-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_alter_account_balance_alter_account_balance_currency",
        ),
        (
            "translation_request",
            "0003_alter_translationrequestmessage_timestamp",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="translationrequest",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, verbose_name="languages"
            ),
        ),
        migrations.AlterField(
            model_name="translationrequestmessage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.user",
            ),
        ),
    ]
