# Generated by Django 4.2.8 on 2023-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation_request", "0004_translationrequest_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="translationrequestmessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="timestamp"
            ),
        ),
    ]
