# Generated by Django 4.2.8 on 2023-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translationrow",
            old_name="row_str",
            new_name="msg_id",
        ),
        migrations.RemoveField(
            model_name="translationrow",
            name="row_id",
        ),
        migrations.AddField(
            model_name="translationrow",
            name="msg_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translationrow",
            name="msg_str",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="translationrow",
            constraint=models.UniqueConstraint(
                fields=("msg_context", "msg_id"), name="unique_row"
            ),
        ),
    ]
