# Generated by Django 4.2.8 on 2023-12-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_rename_row_str_translationrow_msg_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_activity",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="last activity"
            ),
        ),
        migrations.AlterField(
            model_name="projectlanguage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="projects.project",
            ),
        ),
    ]
