# Generated by Django 4.2.8 on 2023-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_last_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_activity",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="last activity"
            ),
        ),
        migrations.AlterField(
            model_name="translationcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="translationrow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="translationrow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
