# Generated by Django 4.2.7 on 2023-12-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_created_at_alter_project_last_activity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="translationrow",
            name="unique_row",
        ),
        migrations.AddConstraint(
            model_name="translationrow",
            constraint=models.UniqueConstraint(
                fields=(
                    "msg_str",
                    "msg_id",
                    "msg_context",
                    "translation_file",
                ),
                name="unique_row",
            ),
        ),
    ]
