# Generated by Django 4.2.7 on 2023-12-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_translationrow_unique_row_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationrow",
            name="occurrences",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
