# Generated by Django 4.2.8 on 2023-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="about",
            field=models.TextField(
                blank=True, null=True, verbose_name="about"
            ),
        ),
    ]
