# Generated by Django 4.2.6 on 2023-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="blocked",
            field=models.BooleanField(default=False, verbose_name="blocked"),
        ),
        migrations.AddField(
            model_name="account",
            name="blocked_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="blocked reason"
            ),
        ),
    ]
