# Generated by Django 4.2.8 on 2023-12-16 08:50

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_native_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=djmoney.models.fields.MoneyField(
                currency_choices=(("USD", "Dollar"),),
                decimal_places=4,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=19,
                verbose_name="balance",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
